### PR TITLE
particle-emitter - add the component and inflator

### PR DESCRIPTION
**Pull request by uhunkler**
and the related files. Plus the "lib-hubs": "github:mozillareality/lib-hubs#master" dependency.

### CODE REVIEW

**Review by vincentfretin — CHANGES_REQUESTED** [review]
Thanks!
You can remove the examples/playground/625d696f-1264-4616-8ac9-72b205ed3e63.png file from this PR.
Replace 
`this.setTexture(data.src, data.resolve).catch(console.error);`
by
`this.setTexture(data.src).catch(console.error);`
and modify the link to the blend file in examples/index.html

**Comment by uhunkler** [comment]
When I remove  examples/playground/625d696f-1264-4616-8ac9-72b205ed3e63.png the particle image will not be loaded. I tried to use the link to the particle image in the CDN but that does not work. The sounds linked from an external URL also needed to be saved in the playground folder. 

Which URL to the particle image do you think would work without saving it in the playground folder?

**Comment by vincentfretin** [comment]
Ah it's in your playground folder, I thought it was in outdoor-festival. Ok keep it in the folder then.
And in outdoor-festival scene, is it working from the cdn? The sounds are working, so I don't see why the image won't work.

**Comment by vincentfretin** [comment]
If you use https://cdn.jsdelivr.net/gh/c-frame/outdoor-festival@d3e76c8/625d696f-1264-4616-8ac9-72b205ed3e63.png in your playground scene, it should work, but yeah keep the file locally like the other files.

**Comment by vincentfretin** [comment]
We may need to set `.setCrossOrigin('anonymous')` on the loader.
```js
 const textureLoader = new TextureLoader().setCrossOrigin('anonymous');
 const texture = await textureLoader.loadAsync(src);
```

This is what hubs and aframe do on their loaders.

**Comment by uhunkler** [comment]
> If you use https://cdn.jsdelivr.net/gh/c-frame/outdoor-festival@d3e76c8/625d696f-1264-4616-8ac9-72b205ed3e63.png in your playground scene, it should work, but yeah keep the file locally like the other files.

When I use that link I get an event error. Even when I add setCrossOrigin('anonymous') on the loader. The CDN link should  work, I know, but for any reason it doesn't.

**Pull request merged**
